edition: developer
monitoringPasscode: "zs-securepasscode"
service:
  type: NodePort
  port: 9000
  nodePort: 30000
persistence:
  enabled: true
  size: 10Gi
resources:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 4Gi
    cpu: 1