---
- name: Clone Node.js repository
  git:
    repo: "https://github.com/rambler-digital-solutions/rship.git"
    dest: "/home/vagrant/nodejs"
    version: master
    force: yes

- name: Clone PHP repository
  git:
    repo: "https://github.com/MadExploits/Gecko.git"
    dest: "/home/vagrant/php"
    version: master
    force: yes

- name: Clone Magento repository
  git:
    repo: "https://github.com/magento/magento2.git"
    dest: "/home/vagrant/magento"
    version: master
    force: yes

- name: Clone Python repository
  git:
    repo: "https://github.com/Toxic-Noob/ToxicBomber.git"
    dest: "/home/vagrant/python"
    version: master
    force: yes